name: Tests (SIMD)

on:
  push:
  # pull_request:

env:
  GOEXPERIMENT: simd
  GOWORK: off

jobs:
  test-simd:
    # GitHub hosted runners run on several architectures.
    # Using Ubicloud ensures we run on AVX512.
    runs-on: ubicloud-standard-2
    strategy:
      fail-fast: false
      matrix:
        go:
          - "stable"

    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Prepare enterprise license for CI
        run: |
          cp ee/fixtures/license/private.ci.key ee/pkg/license/private.key
          cp ee/fixtures/license/public.ci.key ee/pkg/license/public.key

      - name: Test
        run: make test

      - name: Benchmark
        run: |
          cd plugins/exp/simd/
          GOWORK=off GOEXPERIMENT=simd go test -run=^Benchmark -benchmem -bench ./...
